export const DEFAULT_PROFILE_IMAGE = '/images/default_profile_image.jpg';
export const LOGO_IMAGE = '/images/logo_image.svg';
export const FAVICON = '/favicon.ico';

// IMAGE
export const DEFAULT_POST_IMAGE_WIDTH = 600;
export const DEFAULT_POST_IMAGE_HEIGHT = 360;

export const DEFAULT_PROFILE_IMAGE_SIZE = 36;

export const USER_INFO_PROFILE_IMAGE_SIZE = 128;

export const SUGGESTION_PROFILE_IMAGE_SIZE = 64;

export const USER_SETTING_PROFILE_IMAGE_SIZE = 168;

export const LOGO_IMAGE_WIDTH = 90;
export const LOGO_IMAGE_HEIGHT = 24;

export const POST_WRITE_PREVIEW_IMAGE_WIDTH = 100;
export const POST_WRITE_PREVIEW_IMAGE_HEIGHT = 100;

export const COMMENT_PROFILE_IMAGE_SIZE = 28;

export const DETAIL_POST_IMAGE_WIDTH = 700;
export const DETAIL_POST_IMAGE_HEIGHT = 700;

// BUTTON
export const LOGO_BUTTON_WIDTH = 144;
export const LOGO_BUTTON_HEIGHT = 48;

export const DEFAULT_BUTTON_MARGIN = 8;
export const DEFAULT_BUTTON_PADDING = 16;

export const FLOATING_BUTTON_WIDTH = 64;
export const FLOATING_BUTTON_HEIGHT = 64;

export const SOCIAL_BUTTON_WIDTH = 64;
export const SOCIAL_BUTTON_HEIGHT = 64;

export const COMMENT_LIKE_BUTTON_SIZE = 20;
export const COMMENT_LIKE_BUTTON_PADDING = 8;
export const COMMENT_LIKE_BUTTON_MARGIN = 8;
export const COMMENT_PROFILE_IMAGE_BUTTON_MARGIN_RIGHT = 8;
export const COMMENT_USERNAME_BUTTON_MARGIN_RIGHT = 8;

export const POST_PROFILE_IMAGE_BUTTON_MARGIN_RIGHT = 8;
export const POST_USERNAME_BUTTON_MARGIN_RIGHT = 8;

export const DETAIL_PROFILE_SET_MARGIN_LEFT = 8;

// ICON
export const SOCIAL_ICON_SIZE = 48;

export const DEFAULT_ICON_SIZE = 24;

export const DETAIL_COMMENT_ICON_SIZE = 18;

export const DETAIL_COMMENT_ICON_PADDING = 12;

// INPUT
export const SEARCH_INPUT_WIDTH = 136;

export const DEFAULT_COMMENT_INPUT_WIDTH = 340;

export const DETAIL_COMMENT_INPUT_WIDTH = 150;

// CARD
export const POST_CARD_WIDTH = 600;

export const SIGNIN_CARD_WIDTH = 500;

export const SUGGESTION_CARD_WIDTH = 800;

export const USER_INFO_CARD_WIDTH = 500;

export const USER_SETTING_CARD_WIDTH = 800;

// POST
export const POST_CONTENT_LIMIT_LENGTH = 100;
export const DEFAULT_POST_CONTENT_WIDTH = 575;
export const DETAIL_POST_CONTENT_WIDTH = 400;

// COUNT
export const SUGGESTION_COUNT = 3;
