// IMAGE
export const DEFAULT_POST_IMAGE_WIDTH = 600;
export const DEFAULT_POST_IMAGE_HEIGHT = 360;

export const DEFAULT_PROFILE_IMAGE_SIZE = 36;

export const USER_INFO_PROFILE_IMAGE_SIZE = 168;
export const USER_INFO_PROFILE_IMAGE_MARGIN_RIGHT = 16;

export const SUGGESTION_PROFILE_IMAGE_SIZE = 64;

export const USER_SETTING_PROFILE_IMAGE_SIZE = 168;

export const LOGO_IMAGE_WIDTH = 90;
export const LOGO_IMAGE_HEIGHT = 24;

export const POST_WRITE_PREVIEW_IMAGE_WIDTH = 100;
export const POST_WRITE_PREVIEW_IMAGE_HEIGHT = 100;

export const COMMENT_PROFILE_IMAGE_SIZE = 28;

export const DETAIL_POST_IMAGE_WIDTH = 1000;
export const DETAIL_POST_IMAGE_HEIGHT = 1000;

// BUTTON
export const LOGO_BUTTON_WIDTH = 144;
export const LOGO_BUTTON_HEIGHT = 48;

export const DEFAULT_BUTTON_MARGIN = 8;
export const DEFAULT_BUTTON_PADDING = 16;

export const FLOATING_BUTTON_WIDTH = 64;
export const FLOATING_BUTTON_HEIGHT = 64;

export const SOCIAL_BUTTON_WIDTH = 64;
export const SOCIAL_BUTTON_HEIGHT = 64;

export const COMMENT_LIKE_BUTTON_SIZE = 20;
export const COMMENT_LIKE_BUTTON_PADDING = 8;
export const COMMENT_LIKE_BUTTON_MARGIN = 8;
export const COMMENT_PROFILE_IMAGE_BUTTON_MARGIN_RIGHT = 8;
export const COMMENT_USERNAME_BUTTON_MARGIN_RIGHT = 8;
export const COMMENT_USERNAME_BUTTON_WIDTH = 90;

export const POST_PROFILE_IMAGE_BUTTON_MARGIN_RIGHT = 8;
export const POST_USERNAME_BUTTON_MARGIN_RIGHT = 8;

export const DETAIL_PROFILE_SET_MARGIN_LEFT = 8;

export const DELETE_BUTTON_SIZE = 20;
export const DELETE_BUTTON_PADDING = 8;

export const NAVIGATE_BUTTON_PADDING = 16;

export const RETURN_BUTTON_SIZE = 25;

export const DASHBOARD_DELETE_BUTTON_WIDTH = 36;
export const DASHBOARD_DELETE_BUTTON_HEIGHT = 36;

// ICON
export const SOCIAL_ICON_SIZE = 48;

export const DEFAULT_ICON_SIZE = 24;

export const DASHBOARD_USER_INFO_ICON_SIZE = 24;

export const DASHBOARD_SETTING_ICON_BUTTON_WIDTH = 60;

export const DASHBOARD_SETTING_ICON_BUTTON_HEIGHT = 60;

// INPUT
export const SEARCH_INPUT_WIDTH = 136;

export const DEFAULT_COMMENT_INPUT_WIDTH = 340;

export const HISTORY_INPUT_WIDTH = 150;

// CARD
export const SIGNIN_CARD_WIDTH = 500;

export const SUGGESTION_CARD_WIDTH = 800;

export const USER_INFO_CARD_WIDTH = 600;

export const USER_SETTING_CARD_WIDTH = 600;

export const EXTERNAL_AUTH_CARD_WIDTH = 600;

export const DASHBOARD_LEFT_SECTION_CARD_WIDTH = 740;
export const DASHBOARD_RIGHT_SECTION_CARD_WIDTH = 500;
export const DASHBOARD_STATISTICS_CARD_HEIGHT = 350;

export const NOTIFY_CARD_WIDTH = 600;
export const NOTIFY_CARD_HEIGHT = 80;

// POST
export const POST_WIDTH = 600;

export const POST_CONTENT_LIMIT_LENGTH = 100;

export const POST_CONTENT_WIDTH = 575;

// MODAL
export const DELETE_MODAL_TITLE_HEIGHT = 50;

export const DEFAULT_MODAL_WIDTH = 384;

// COUNT
export const SUGGESTION_COUNT = 3;

// TIME
export const TIME_MIN_WIDTH = 40;

// DASHBOARD
export const DASHBOARD_HISTORY_MARGIN_LEFT = 50;
export const DASHBOARD_STACK_TITLE_FONT_SIZE = 16;

export const RADAR_CHART_WIDTH = 30;
export const RADAR_CHART_HEIGHT = 30;
export const PIE_CHART_WIDTH = 300;
export const PIE_CHART_HEIGHT = 300;

// TIME
export const DEFAULT_DEBOUNCE_TIME = 200;
