import type { ReactElement } from 'react';
import Head from 'next/head';

function Home(): ReactElement {
  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>home</main>

      <footer />
    </div>
  );
}

export default Home;
