import type { ReactElement } from 'react';
import Head from 'next/head';

function Random(): ReactElement {
  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>random</main>

      <footer />
    </div>
  );
}

export default Random;
