import type { ReactElement } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

function Story(): ReactElement {
  const { storyID } = useRouter().query;

  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>Story {storyID}</main>

      <footer />
    </div>
  );
}

export default Story;
