import Head from 'next/head';

import Header from 'src/components/Header';
import UserInfo from 'src/components/UserInfo';
import Timeline from 'src/components/Timeline';
import { Col } from 'src/components/Grid';

import { UserType } from 'src/types';

import { Fetcher } from 'src/utils';

import { Main } from 'src/styles/pages/users/user';

interface Props {
  user: UserType;
  isMe: boolean;
}

function User({ user, isMe }: Props) {
  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Main>
        <Col>
          <UserInfo user={user} />
          <Timeline />
        </Col>
      </Main>

      <footer />
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const { username } = context.query;
  const token = context.req?.cookies.jwt;
  const user: UserType = await Fetcher.getUsersByUsername(token, username);
  console.log(user);
  return {
    props: { user: { ...user, token } },
  };
}

export default User;
