import Head from 'next/head';
import { useQuery } from 'react-query';

import Header from 'src/components/Header';
import UserInfo from 'src/components/UserInfo';
import Timeline from 'src/components/Timeline';
import { Col } from 'src/components/Grid';

import { UserType, PostType } from 'src/types';

import { Fetcher } from 'src/utils';

import { Main } from 'src/styles/pages/users/user';

interface Props {
  user: UserType;
  targetUser: UserType;
}

function User({ user, targetUser }: Props) {
  const { data } = useQuery<PostType[]>(['posts', targetUser._id], () =>
    Fetcher.getUsersPosts(user),
  );

  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Main>
        <Col>
          <UserInfo user={targetUser} />
          <Timeline posts={data} />
        </Col>
      </Main>

      <footer />
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const { username } = context.query;
  const token = context.req?.cookies.jwt;
  if (token === undefined) {
    return {
      redirect: {
        permanent: true,
        destination: '/',
      },
    };
  }
  const usersByUsernameRequest = Fetcher.getUsersByUsername(token, username);
  const usersMeRequests = Fetcher.getUsersMe(token);
  const targetUser = await usersByUsernameRequest;
  const user = await usersMeRequests;
  return {
    props: { user: { ...user, token }, targetUser },
  };
}

export default User;
