import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';

function User() {
  const { userID } = useRouter().query;

  return (
    <div>
      <Head>
        <title>COCOO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        User {userID}
        <br />
        밑에 클릭하면 이동
        <br />
        <Link href='/dashboard'>dashboard</Link>
        <br />
        <Link href='/setting'>setting</Link>
      </main>

      <footer />
    </div>
  );
}

export default User;
